### ISSUE TITLE
Allow credential impersonation

### ISSUE THREAD

**Issue by gunar** [GoogleCloudPlatform/cloud-sql-python-connector#223]
Would like to use service account impersonation.

I've executed ` gcloud auth application-default login --impersonate-service-account=<name>@<project>.iam.gserviceaccount.com`.

Currently, using the library throws:

```
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: The file /home/gcg/.config/gcloud/application_default_credentials.json does not have a valid type. Type is impersonated_service_account, expected one of ('authorized_user', 'service_account', 'external_account').
```

**Comment by jackwotherspoon** [comment]
@gunar Adding support for service account credentials is being tracked in a separate issue #171. Will close this as it is a duplicate. Thanks for the feedback!

**Comment by kurtisvg** [comment]
@jackwotherspoon I think impersonation and specify the service account credentials are probably different enough to have different items tracking

**Comment by gunar** [comment]
Did #226 implement this feature?

**Comment by jackwotherspoon** [comment]
@gunar Not fully no. You can now pass in a credentials object to a custom `connector.Connector()` object that will use the specified credentials to authenticate instead of default credentials. So theoretically yes you could pass in an impersonated credentials using the following method [google.auth.impersonated_credentials](https://google-auth.readthedocs.io/en/master/reference/google.auth.impersonated_credentials.html).

I will be adding support for the gcloud command that you mentioned above to work natively with the connector in the coming weeks. Hope that clarifies it! Thanks for asking :)

All the best.
