### ISSUE TITLE
Creating connection fails with "There is no current event loop in thread 'ThreadPoolExecutor-0_0'"

### ISSUE THREAD

**Issue by Rklangrin** [GoogleCloudPlatform/cloud-sql-python-connector#240]
## Bug Description

When creating connection using the `google.cloud.sql.connector`, I run into the following error. "There is no current event loop in thread 'ThreadPoolExecutor-0_0'". This was not the case 3 days ago before the 0.5.0 version was released. I was using 0.4.1, but that broke as well. 

## Example code (or command)

```python
from google.cloud.sql.connector import connector

connector.connect(instance_connection_string=instance_connection_string, driver="pg8000", user=username, password=password, db=db_name)
```

## Stacktrace
```
File "/layers/google.python.pip/pip/lib/python3.8/site-packages/leaguestock_player_index_processor/CloudSqlUtility.py", line 14, in __init__
    self.connection = connector.connect(instance_connection_string=instance_connection_string,
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/sql/connector/connector.py", line 176, in connect
    return _default_connector.connect(instance_connection_string, driver, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/sql/connector/connector.py", line 116, in connect
    icm = InstanceConnectionManager(
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/sql/connector/instance_connection_manager.py", line 277, in __init__
    self._refresh_rate_limiter = AsyncRateLimiter(
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/sql/connector/rate_limiter.py", line 49, in __init__
    self._lock = asyncio.Lock()
  File "/opt/python3.8/lib/python3.8/asyncio/locks.py", line 164, in __init__
    self._loop = events.get_event_loop()
  File "/opt/python3.8/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'."
```

## How to reproduce

  1. Call connector.connect with appropriate arguments

## Environment

1. OS type and version: This runs from gcp cloud functions with python38 runtime
2. Python version: 3.8.2
2. Connector version: 0.5.0 AND 0.4.1 (0.4.1. was working until 0.5.0 was released)

**Comment by jackwotherspoon** [comment]
@Rklangrin Thanks for raising this. I'll look into the issue and put out a fix as soon as possible if need be. It is strange that the older version 0.4.1 is no longer working for you, the newer version shouldn't have any effect on the older one. I'll look into it as well and keep you posted! Thanks.

**Comment by Rklangrin** [comment]
I thought that was strange as well. It's possibly a coincidence. The facts are that the connect call started failing 3 days ago when I redeployed the functions (nothing changed in the code, they just redeployed as a side-effect of the CICD pipeline getting triggered).

Anyways, happy to help in any way I can. Feel free to reach out if you have questions.

**Comment by jackwotherspoon** [comment]
@Rklangrin could you do me a huge favor and provide me with the rest of the code sample you are seeing this issue with? What is the query or command you are executing using the connector object? Any insights would be greatly appreciated.

Let me know. Thanks :)

**Comment by jackwotherspoon** [comment]
@Rklangrin Seems like you found two bugs in one! I was able to replicate both the Python Connector bug and the package version upgrade/downgrade bug.

I will work on a fix for the Python Connector event loop bug and get it merged in soon. 

I will also report to the Cloud Functions team the fact that changing a package version to an older version from a newer one doesn't seem to install the older version, seems like a caching issue.

In the meantime a solution to get your Cloud Function working again is by doing the following:

1. Have your `requirements.txt` have the python connector version set to `cloud-sql-python-connector[pg8000]==0.4.1` 
2. Either deploy a brand new Cloud Function with Python 3.8 and your code or change and deploy your current function with Python 3.9 and then re-deploy again with 3.8. (this will reset the package and clear the cache)

Let me know if this works for you. Thanks so much for raising this bug and sorry for any inconvenience it may have caused.

Have a great day - Jack

**Comment by mikepietruszka** [comment]
I'm having this issue as well. I'm available to help out if needed. @jackwotherspoon, thank you for the solutions...I can admit that solution 1 worked for now.

**Comment by roden23** [comment]
Hi, same issue here. 

@jackwotherspoon - Just a note. This is only happening in Cloud Functions. When running the same code locally, all works fine. Not sure if that helps.

**Comment by jackwotherspoon** [comment]
@Rklangrin @mikepietruszka @roden23 Thanks everyone for the comments and feedback, much appreciated.

I am currently working on a fix for this issue. It seems that when support for Python 3.10 was added and we removed the deprecated `loop` param from `asyncio.Lock()` that some unintended side effects have arisen. The main one being that when the connector is called from a thread other than Python's MainThread we see the issue and error message in question. Cloud Functions and Cloud Run call the connector and any code from a `ThreadPoolExecutor` thread, while locally and in our tests the connector runs from Python's MainThread. I will add some tests with the fix to this issue to cover these cases going forward.

I believe the heart of the issue arises from the fact that `asyncio.Lock()` only has access to the current thread's event loop. When we used to pass it the `loop` parameter we were passing it in an event loop running in a background thread and not in the current thread. Therefore, now when `asyncio.Lock()` looks for the event loop in the current thread in Cloud Functions and Cloud Run it fails because there is no event loop, it is in a background thread. This doesn't cause any errors locally because if the current thread is Python's MainThread it has the ability to create an event loop and then use it. 

I am working on a fix to make sure the event loop remains in the background thread and that it can also be accessed in a thread-safe manner. I will keep you all posted and link the PR with the fix to this issue when it is pushed. I will make sure this is resolved by the next release. Thanks once again for raising and addressing this issue. I extremely appreciate it.

All the best -Jack
