### ISSUE TITLE
TypeError: connect() takes 2 positional arguments but 4 were given 

### ISSUE THREAD

**Issue by kotharismeeet** [GoogleCloudPlatform/cloud-sql-python-connector#293]
TypeError: connect() takes 2 positional arguments but 4 were given, **Trying according to documentation tweaking a little bit** 
```
from google.cloud.sql.connector import connector
import sqlalchemy

def getCloudSQLConnection(region,user,password,dbname):
    conn: pymysql.connections.Connection =  connector.connect(region,'pymysql',user,password,db=dbname)
    return conn

def getPool(region,user,password,dbname):
    pool = sqlalchemy.create_engine(
        "mysql+pymysql://",
        creator=getCloudSQLConnection(region,user,password,dbname),
    )
    return pool
```

**Comment by jackwotherspoon** [comment]
@kotharismeeet Hi there, thanks for raising a question on the Cloud SQL Python Connector. 

The error you are seeing is due to `user` and `password` being passed in as positional arguments, while they should be passed in as keyword arguments to the `connect` method.

Updating your `getCloudSQLConnection` function to the following should resolve the error.
```python
def getCloudSQLConnection(region,user,password,dbname):
    conn: pymysql.connections.Connection =  connector.connect(region,'pymysql',user=user,password=password,db=dbname)
    return conn
```

Let me know if this helps resolve your question or if you have any follow up questions. Thanks for using the Cloud SQL Python Connector! Have a great day :)

**Comment by kotharismeeet** [comment]
@jackwotherspoon Tysm
