### ISSUE TITLE
Question regarding the communication step with Cloud SQL Admin in the context of Cloud Dataflow

### ISSUE THREAD

**Issue by GodefroyClair** [GoogleCloudPlatform/cloud-sql-python-connector#570]
## Question
What's your question? Please provide as much relevant information as possible
to reduce turnaround time. 

We are trying to understand what is the protocol of communication with Cloud SQL Admin because we have a 529 "too many requests" error from Cloud SQL Admin using a Dataflow streaming system.

```
['XXX']: An error occurred while performing refresh. Scheduling another refresh attempt immediately Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/google/cloud/sql/connector/instance.py", line 403, in _refresh_task refresh_data = await refresh_task File "/usr/local/lib/python3.9/site-packages/google/cloud/sql/connector/instance.py", line 328, in _perform_refresh metadata = await metadata_task File "/usr/local/lib/python3.9/site-packages/google/cloud/sql/connector/refresh_utils.py", line 103, in _get_metadata resp = await client_session.get(url, headers=headers, raise_for_status=True) File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 643, in _request resp.raise_for_status() File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status raise ClientResponseError( aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://sqladmin.googleapis.com/sql/v1beta4/projects/XXX/instances/YYY/connectSettings')
```
## Additional Context
Please reference any other relevant issues, PRs, descriptions, or screenshots here.
We run a small streaming Cloud Dataflow pipeline with a few "doFn" steps where we connect to a Cloud SQL PG with this connector. If we only use 2 workers, we get very quickly flooded with "too many requests" error messages... It is probably related to our usage of Dataflow and the lifecycle of the the DoFn but we would like to understand why and how the connector connects to CLoud SQL Admin... IF it is for auth reason, is it possible to share the auth token/cert... between the DoFn without sharing the connection ?
T

**Comment by jackwotherspoon** [comment]
@GodefroyClair Thanks for raising a question on the Cloud SQL Python Connector! 😄 

To understand your use-case a little more do you mind sharing a snippet of your application code where you are using the Connector? Are you using connection pooling with SQLAlchemy?

> we would like to understand why and how the connector connects to Cloud SQL Admin...

The Cloud SQL connector makes two calls to Cloud SQL Admin APIs on the initial call to [`connector.connect()`](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/google/cloud/sql/connector/connector.py#L156) for a Cloud SQL instance to fetch the instance's metadata as well as a cert (also calls these APIs every 1 hour after initialization to refresh the metadata and cert). You can find these two API calls within [`refresh_utils.py`](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/google/cloud/sql/connector/refresh_utils.py)

If you are initializing new connector object within each `doFn` step this may potentially be the cause of your issue as it will cause you to call the Cloud SQL Admin APIs on every new connection. You might look to pass in a Connector object to `doFn` in order to help re-use connections.

If you are able to provide a bit more context surrounding your application code I should be able to provide a bit more detailed assistance.

Have a great day - Jack

**Comment by GodefroyClair** [comment]
Thank you  for your help Jack. Yes we are using SQLAlchemy. We are using a
pooling connection. But also we've made some tests with a non pooling one.
Here is the Class we are using. We are following the recommendation to use
put the connection in the setup and the closing of the connection in the
finish_bundle.

Le mer. 21 déc. 2022 à 20:40, Jack Wotherspoon ***@***.***> a
écrit :

**Comment by jackwotherspoon** [comment]
Hi @GodefroyClair thanks for the response. Did you mean to paste your code snippet in the above response? Or you can link me to a public repo if that is easier. It is hard to determine the root cause of the issue without seeing the code.

Let me know as I will happily take a look for you. 

Note: Might be a bit slow to respond over the next week as most of our team will be off for holidays.

**Comment by GodefroyClair** [comment]
I added a py file to my answer but it probably got filtered out. I'm
just gonna paste it in the body of the email under. FYI, all doFN that have
to connect to Cloud SQL inherit from this class. If you need, I can also
send you the main pipeline code.


import logging
import time

import apache_beam as beam
from google.cloud.sql.connector import Connector, IPTypes
from sqlalchemy import create_engine
from sqlalchemy.exc import OperationalError

from src.config.constants import (
    INSTANCE_CONNECTION_NAME, DB_USER, DB_PASS, DB_NAME,
    CONN_STRING, USE_POOL, POOL_SIZE, CHUNK_SIZE)


class CloudSqlDoFn(beam.DoFn):
    def __init__(
        self,
        local
    ):
        self.local = local

        self.connected_pool = None
        self.connected_conn = None

        self.instance_connexion_name = INSTANCE_CONNECTION_NAME
        self.db_user = DB_USER
        self.db_pass = DB_PASS
        self.db_name = DB_NAME

        self.use_pool = USE_POOL
        self.pool_size = POOL_SIZE
        self.chunk_size = CHUNK_SIZE

        self.local_conn_string = CONN_STRING

    def get_conn(self):
        """Create connexion"""
        conn = None
        # initialize connector
        while conn is None:
            try:

                if self.local:
                    engine = create_engine(self.local_conn_string)
                    conn = engine.raw_connection()
                else:
                    conn = Connector().connect(
                        self.instance_connexion_name,
                        "pg8000",
                        user=self.db_user,
                        password=self.db_pass,
                        db=self.db_name,
                        ip_type=IPTypes.PRIVATE
                    )

            except OperationalError as err:
                logging.warning("[GET CONN][ERROR] Cannot connect to DB:
%s", err)

            except Exception as err:

                logging.warning('[GET CONN][ERROR] Unhandled error %s', err)
        return conn

    def get_pool(self):
        """Create pool of connexion"""
        pool = None
        while pool is None:
            try:
                if self.local:
                    pool = create_engine(self.local_conn_string)
                else:
                    pool = create_engine(
                        "postgresql+pg8000://",
                        creator=self.get_conn,
                        pool_size=self.pool_size,
                        pool_recycle=1800
                    )
                return pool
            except RuntimeError:
                time.sleep(1)

            except OperationalError as err:
                logging.warning("[GET POOL][ERROR] Cannot connect to DB:
%s", err)

            except Exception as err:
                logging.warning("[GET POOL][ERROR] Unhandeled error in
get_pool(): %s", err)
                raise

    def setup(self):
        """Open connection or pool of connections to Postgres"""
        try:
            if self.use_pool:
                self.connected_pool = self.get_pool()
                logging.info("[SETUP][DEBUG] Pool opened")
            else:
                self.connected_conn = self.get_conn()
                logging.info("[SETUP][DEBUG] Connexion opened")
        except Exception as err:
            logging.warning(
                "[SETUP][ERROR] Unhandeled error in
WriteToDataBases.setup(): %s", err
            )
            raise

    def finish_bundle(self):
        """Close connection to Postgres"""
        try:
            if self.use_pool:
                self.connected_pool.dispose()
                logging.info("[TEARDOWN][DEBUG] Pool closed")
            else:
                self.connected_conn.close()
                logging.info("[TEARDOWN][DEBUG] Connexion closed")
        except Exception as err:
            logging.warning(
                "[TEARDOWN][ERROR] Unhandeled error in
WriteToDataBases.teardown: %s", err
            )
            raise


if __name__ == "__main__":
    pass



Le jeu. 22 déc. 2022 à 16:18, Jack Wotherspoon ***@***.***> a
écrit :

**Comment by kurtisvg** [comment]
Hey @GodefroyClair,

From the looks of it, it seems like your pool might be getting open/closed more often than it could be. All of the DoFn objects will be using a different python connector, which means they are all making their own API call requests. You should try to cache these resources so they are shared more efficiently. Take a look at [this blog post](https://medium.com/google-cloud/cache-reuse-across-dofns-in-beam-a34a926db848) -- it talks about sharing the resources between DoFn's at the process level.

**Comment by jackwotherspoon** [comment]
Closing for now due to inactivity. If the question still persists, please don't hesitate to re-open the issue and add another comment.

Thanks, 
Jack

**Comment by GodefroyClair** [comment]
Sorry for the time I too to reply. We had other urgent issues to solve :)
We are discussing with some of your colleagues to help us keep the number of connexion requests low (we are already using  connection pool to reduce the number of connections but probably your suggestion to use cache is the answer. We first thought that we could handle the number of connexions by tunning the max number of workers and threads but the formulae that we had in mind doesn't seem to be working.
Anyway, I'd like to understand better our "too many requests" problem. We are far from using the 4000 max connexions to Cloud SQL that are available so I guess the problem is more that the Cloud SQL Admin server is overwhelmed with too many requests _at the same time_. Could you provide us with the performances of this server? How long does it take to serve one answer? How many requests can it handle at the same time?...
I'm sure it has be tuned to fit the needs of Cloud SQL (even though it is the bottleneck for us) but could you provide us with some metrics to help us understand why it was done this way?
Thanks!

**Comment by jackwotherspoon** [comment]
Hi @GodefroyClair, no problem! 

The `429: Too Many Requests` error is most likely caused by hitting the quota for the Cloud SQL Admin API within your GCP project. You can view the quota and metrics for the Cloud SQL Admin API by going to https://console.cloud.google.com/apis/api/sqladmin.googleapis.com/quotas. The quota is measured in requests per minute per user and has a default value of 180. However, you can raise the quota value by clicking "EDIT QUOTAS" in the link provided.

Each Python Connector `Connector()` object initialization makes two requests to Cloud SQL Admin APIs as previously mentioned. So if you are spinning up a lot of Connector objects (~90+) within a minute and have an issue using connection pooling or caching than you may very well be hitting this quota. 

> We are far from using the 4000 max connexions to Cloud SQL that are available

I assume this 4000 is referring to the `max_connections` database flag and not the Cloud SQL Admin API quota? These are two different things and the too many requests is most likely being caused by your Admin API quota and not the number of connections to the database itself. If your application is properly using connection pooling and you are still seeing the errors than I would definitely request a raise to your quota. The default value may be too low for your needs and use case.  

Let me know if that helps clarify things.

Thanks, Jack

**Comment by GodefroyClair** [comment]
Wow that's helpful!! I couldn't find much documentation about Cloud SQL Admin but I forgot to look in the quotas & limits  :-/ Silly me...
So to answer your question, yes we are using pooling and that would be really helpful to see how increasing the quotas improve our performances! I'm gonna ask for 500 queries per minute. Any idea what's the range ?

**Comment by jackwotherspoon** [comment]
@GodefroyClair 

Happy to help! There isn't really an ideal range as the use of the quota is fully dependent on your application. 

As I mentioned briefly in my last comment, every time you initialize a Python Connector object through calling `Connector()` then two Cloud SQL Admin API calls are made (one to get instance metadata and one to generate a cert). So for most use-cases a quota of 180 should be enough as you would only need more if you are initializing more than 90 connector objects for the same user within a minute. If this is not the case for your application then you would probably want to check your application code as it most likely points to a bigger issue being made in the implementation. 

You might want to look at caching the connector objects as mentioned by Kurtis in his comment in order to reduce the Cloud SQL Admin API calls being made each time you initialize a new connector object.

**Comment by GodefroyClair** [comment]
Yeah, I am absolutely aware that too many connections are open :) but Dataflow is such a powerful tool and not too easy to slow done.
Also in the case we are working on, we can have many files arriving at the same time so it is a bit normal Dataflow tries to handle all of them at the same (as it can!).
Actually we are able to run pipelines in certain conditions and be OK but then the performances are really poo.
So far, we have tried to work with `working with max_num_workers` and `number_of_worker_harness_threads` in our streaming pipeline but it doesn't seem to limit "enough" the number of connections. :(

So our next stop is indeed to look into caching the connectors. Just seemed weird we have to do something like this to allow the right number of connexions.

Thanks again!
