### ISSUE TITLE
[DEPENDENCIES] Cannot update google-ads pypi package

### ISSUE THREAD

**Issue by isisplum12** [GoogleCloudPlatform/cloud-sql-python-connector#653]
### Bug Description

I'm trying to update the version of the pypi package google-ads on Google Cloud Composer.

I need to update google-ads to version 19.0.0, which is required to update the version of Google ads API to v12. When I try to set the version to 19.0.0, version problems start to appear with other libraries, mainly the mysql-connector-python, which is native from composer.

Here is some information about the environment that I'm using. Composer version 2.1.7 | Airflow version 2.4.3

I already tried to change the versions of the conflicting libraries, but mysql-connector-python requires an old version of protobuf and google-ads needs a new one, I stay trapped between those two.

Another attempt was deleting the library mysql-connector-python, which the following cli on cloud shell: gcloud --project=my-project-name composer environments update teste --location us-central1 --remove-pypi-packages mysql-connector-python

But I got the following error:

(gcloud.composer.environments.update) INVALID_ARGUMENT: No change in configuration. Must specify a change to configuration.software_configuration.pypi_dependencies.mysql-connector-python

### Steps to reproduce?

The bug show up when I tried to update google-ads library on composer environment 

### Environment

Composer version 2.1.7 | Airflow version 2.4.3

**Comment by jackwotherspoon** [comment]
Hi @isisplum12 Thanks for raising a bug on the Cloud SQL Python Connector!

However, I think you have opened an issue on the wrong repository. This is the repository for the [`cloud-sql-python-connector`](https://pypi.org/project/cloud-sql-python-connector/) pypi package and not the [`mysql-connector-python`](https://pypi.org/project/mysql-connector-python/).

The package you are referencing is owned and published by MySQL itself (Oracle) and not Google.

Here is the [official page for the mysql-connector-python](https://dev.mysql.com/doc/connector-python/en/) which I would recommend checking out to find where to open the proper bug/issue.

Hope this helps, closing issue due to wrong package.

Have a great day! 😄
