### ISSUE TITLE
Access denied for user 'xxx' to database 'abc'

### ISSUE THREAD

**Issue by samshipengs** [GoogleCloudPlatform/cloud-sql-python-connector#770]
### Bug Description

I'm trying out the GCP CloudSQL (MySQL) and this python connector.

I first created a service account and assigned the Cloud SQL Client role to it, then created a database on the Cloud SQL page, assigned the service account email address to the users in the Cloud SQL users section.

I tried using this service account key to connect to this database, it keeps saying "Access denied" 

### Example code (or command)

```Python
# Load the service account json key
service_account_fp = os.getenv("CLOUD_SQL_SERVICE_ACCOUNT_KEY")

cred = service_account.Credentials.from_service_account_file(
    filename=str(service_account_fp)
)

connector = Connector(credentials=cred, enable_iam_auth=True)

# I have a .env file and the constants gets loaded into os envs
sql_connection = os.getenv("CLOUD_SQL_INSTANCE")
cloud_sql_user = os.getenv("CLOUD_SQL_USER")
db_name = os.getenv("CLOUD_SQL_DB")

connector.connect(
    sql_connection,
    "pymysql",
    user=cloud_sql_user,
    db=db_name,
)
```

### Stacktrace

```bash
OperationalError: (1044, "Access denied for user 'cloudsql'@'%' to database 'listings'")

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
Cell In[3], line 1
----> 1 conn = c.pool.connect()
...
    141 if errorclass is None:
    142     errorclass = InternalError if errno < 1000 else OperationalError
--> 143 raise errorclass(errno, errval)

OperationalError: (pymysql.err.OperationalError) (1044, "Access denied for user 'cloudsql'@'%' to database 'listings'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Steps to reproduce?

1. Create a service account and assign Cloud SQL Client to it (also enable the Cloud SQL Admin API (as the [github page]([Cloud SQL Admin API](https://console.cloud.google.com/apis/api/sqladmin.googleapis.com) instructed))
2. Create a MySQL database on the Cloud SQL page on GCP (I tried using the connector, but seems I cannot create the db, so i just clicked create database on the webpage)
3. Assign the service account to the users for this database
4. Run above code

### Environment

1. OS type and version: Ubuntu 22.04.2 LTS Jammy Jellyfish
2. Python version: 3.10.11
3. Cloud SQL Python Connector version: 1.2.4

**Comment by jackwotherspoon** [comment]
Hi @samshipengs thanks for raising an issue on the Cloud SQL Python Connector!

I believe this is actually not a bug with the Connector library but more a permissions issue due to the nature of the error message you are seeing.

As per our [Login with automatic IAM database authentication](https://cloud.google.com/sql/docs/mysql/iam-logins#python) Google Cloud docs: 
> When an IAM user is added to a database, the new database user has no privileges to any database by default. You need to use the GRANT command to give the IAM database user any required permissions. For more information, see [Grant database privileges to the IAM User](https://cloud.google.com/sql/docs/mysql/add-manage-iam-users#grant-db-privileges).

This is most likely the cause of the error you are seeing. Your service account IAM database user upon creation will have no database privileges by default. You will need to use the `root` user to run a `GRANT` statement to grant them any required privileges on your `listings` database.

You can run the `GRANT` command using the Cloud SQL Connector or through the [Cloud Shell (instructions)](https://cloud.google.com/sql/docs/mysql/connect-instance-cloud-shell ) console using 
```sh
gcloud sql connect <INSTANCE_NAME> --user=root
```

The above way is probably the easiest. Otherwise you can use the `Connector` and connect as `root` as follows:
```python
cred = service_account.Credentials.from_service_account_file(
    filename=str(service_account_fp)
)

connector = Connector(credentials=cred, enable_iam_auth=False)

# I have a .env file and the constants gets loaded into os envs
sql_connection = os.getenv("CLOUD_SQL_INSTANCE")
cloud_sql_user = os.getenv("CLOUD_SQL_USER")
db_name = os.getenv("CLOUD_SQL_DB")

connection = connector.connect(
    sql_connection,
    "pymysql",
    user="root",
    password="<root-password>",
    db="",
)
with connection:
    with connection.cursor() as cursor:
        cursor.execute("GRANT SELECT on *.* TO `cloudsql`@`%`")
    connection.commit()
```

After granting `SELECT` privileges on all databases and tables (can also change `*.*` to `listings.*` to reduce privileges) you should now be able to establish a connection to `listings` using the code you previously had.

Hope this helps solve your issue!

Have a great day 😄

**Comment by samshipengs** [comment]
I see, I missed these documentation, thanks! I also need to grant other types of operations that I needed, after which it's working now.
