### ISSUE TITLE
Changing comment style from Google to Sphinx

### ISSUE THREAD

**Issue by fatcat2** [GoogleCloudPlatform/cloud-sql-python-connector#8]
The purpose of this issue is to track the change from Google-style comments to Sphinx-style comments.

**Comment by shubha-rajan** [comment]
So It looks like these are [already Sphinx style docstrings](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/434f717b68d34a3254f47ea1a0dcd10a44dfcb52/google/cloud/sql/connector/InstanceConnectionManager.py#L196). Our other repos, like `python-storage` also seem to be using Sphinx. Gonna close this one since it looks like it's already done.
